#!/usr/bin/env python3
"""Regenerate the documentation search index (assets/search-index.js).

Scans every page of the static docs site for its <title> and for h2/h3
headings with id attributes, and emits a window.SEARCH_INDEX array that
assets/docs.js searches client-side. Stdlib only; run from anywhere:

    python3 docs/site/tools/build_search_index.py
"""

import html
import json
import re
import sys
from pathlib import Path

SITE = Path(__file__).resolve().parent.parent
PAGES = sorted(
    p for p in SITE.rglob("*.html")
    if "tools" not in p.parts
)

TITLE_RE = re.compile(r"<title>(.*?)</title>", re.S)
HEAD_RE = re.compile(r"<h([23])\s+id=\"([^\"]+)\"[^>]*>(.*?)</h\1>", re.S)
TAG_RE = re.compile(r"<[^>]+>")
# Paragraph/list text following a heading is not indexed to keep the file small;
# headings + titles give good-enough recall for a site of this size.


def clean(text: str) -> str:
    return html.unescape(TAG_RE.sub("", text)).strip()


def main() -> int:
    entries = []
    for page in PAGES:
        rel = page.relative_to(SITE).with_suffix("").as_posix()
        src = page.read_text(encoding="utf-8")
        m = TITLE_RE.search(src)
        title = clean(m.group(1)).split("—")[0].strip() if m else rel
        entries.append({"page": rel, "title": title, "section": "", "anchor": "", "text": title})
        for _lvl, anchor, heading in HEAD_RE.findall(src):
            section = clean(heading).replace("¶", "").strip()
            entries.append({
                "page": rel,
                "title": title,
                "section": section,
                "anchor": anchor,
                "text": f"{title} {section}",
            })
    out = SITE / "assets" / "search-index.js"
    payload = json.dumps(entries, indent=0, ensure_ascii=False)
    out.write_text(
        "/* Generated by tools/build_search_index.py — do not edit by hand. */\n"
        f"window.SEARCH_INDEX = {payload};\n",
        encoding="utf-8",
    )
    print(f"wrote {out} ({len(entries)} entries from {len(PAGES)} pages)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
