#!/usr/bin/env bash
# install_open_dis.sh — build the third-party open-dis-cpp DIS library (pinned
# upstream release v1.2.0, BSD-2-Clause) as a static library and install it
# into a prefix, instead of vendoring its sources in this repository.
#
#   scripts/install_open_dis.sh [--prefix DIR] [--src DIR]
#
# Installs:
#   $PREFIX/include/dis6/...                 headers (incl. utils/ and a
#                                            generated no-op opendis6_export.h)
#   $PREFIX/lib/libopendis6.a                static library (dis6 tree only)
#   $PREFIX/share/doc/open-dis-cpp/LICENSE   BSD-2-Clause text + provenance
#
# cmake/open_dis_cpp.cmake finds this install (default search: /usr/local,
# /opt/open-dis, ~/.local; override with -DOLV_OPEN_DIS_PREFIX=DIR).
#
# Source acquisition, in order of preference:
#   --src DIR                    an already-unpacked open-dis-cpp source tree
#   $OLV_OPEN_DIS_TARBALL        path to a pre-fetched release tarball (air gap:
#                                mirror the tarball like the apt packages)
#   $OLV_OPEN_DIS_URL            alternate download URL (e.g. an internal
#                                mirror); the pinned sha256 is still enforced
#   (otherwise)                  download the pinned tag from GitHub
# The downloaded/pre-fetched tarball is checked against the pinned sha256
# before anything is compiled.
#
# Only the self-contained src/dis6/ tree (protocol version 6, C++ standard
# library only) is built, with warnings suppressed (-w): it is auto-generated
# upstream via xmlpg. dis7/, examples/ (which need SDL2), and tests are not
# built. Upstream sources are compiled verbatim — no local patches; any fix
# goes upstream or waits for a new pinned tag.

set -euo pipefail

VERSION="1.2.0"
TARBALL_URL="https://github.com/open-dis/open-dis-cpp/archive/refs/tags/v${VERSION}.tar.gz"
TARBALL_SHA256="aa1b9b5e5f00e5b8819c111f0a5a0e56266c7ccc0ec9b9f5b9d33f7721438216"

PREFIX="/usr/local"
SRC_DIR=""

while [ $# -gt 0 ]; do
  case "$1" in
    --prefix) PREFIX="$2"; shift 2 ;;
    --src)    SRC_DIR="$2"; shift 2 ;;
    -h|--help) sed -n '2,30p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "install_open_dis.sh: unknown argument: $1" >&2; exit 1 ;;
  esac
done

CXX="${CXX:-g++}"
AR="${AR:-ar}"
WORK="$(mktemp -d)"
trap 'rm -rf "${WORK}"' EXIT

# ---- Obtain the pinned source tree ----------------------------------------
if [ -z "${SRC_DIR}" ]; then
  TARBALL="${OLV_OPEN_DIS_TARBALL:-}"
  if [ -z "${TARBALL}" ]; then
    TARBALL="${WORK}/open-dis-cpp-v${VERSION}.tar.gz"
    URL="${OLV_OPEN_DIS_URL:-${TARBALL_URL}}"
    echo "fetching ${URL}"
    curl -fsSL -o "${TARBALL}" "${URL}"
  fi
  echo "${TARBALL_SHA256}  ${TARBALL}" | sha256sum -c - >/dev/null
  tar xzf "${TARBALL}" -C "${WORK}"
  SRC_DIR="${WORK}/open-dis-cpp-${VERSION}"
fi

DIS6_SRC="${SRC_DIR}/src"
[ -d "${DIS6_SRC}/dis6" ] || { echo "install_open_dis.sh: ${DIS6_SRC}/dis6 not found" >&2; exit 1; }

# ---- Generate the export header (upstream generates it with CMake; for a
#      static library the OPENDIS6_EXPORT macros expand to nothing) ----------
GEN="${WORK}/gen"
mkdir -p "${GEN}/dis6"
cat > "${GEN}/dis6/opendis6_export.h" <<'EOF'
/* opendis6_export.h — generated by scripts/install_open_dis.sh for a static
 * build; all export/import macros are no-ops. */
#ifndef OPENDIS6_EXPORT_H
#define OPENDIS6_EXPORT_H
#define OPENDIS6_EXPORT
#define OPENDIS6_NO_EXPORT
#define OPENDIS6_DEPRECATED
#define OPENDIS6_DEPRECATED_EXPORT
#define OPENDIS6_DEPRECATED_NO_EXPORT
#endif
EOF

# ---- Compile src/dis6 (recursively) into libopendis6.a ---------------------
BUILD="${WORK}/build"
mkdir -p "${BUILD}"
echo "compiling dis6 with ${CXX} (-O2, static)"
JOBS="$(nproc 2>/dev/null || echo 4)"
export CXX DIS6_SRC GEN BUILD
find "${DIS6_SRC}/dis6" -name '*.cpp' -print0 |
  xargs -0 -P "${JOBS}" -n 1 sh -c '
    rel="${0#"${DIS6_SRC}"/}"
    obj="${BUILD}/$(printf %s "${rel}" | tr / _).o"
    exec "${CXX}" -O2 -w -std=c++17 -c "$0" -I "${DIS6_SRC}" -I "${GEN}" -o "${obj}"
  '
"${AR}" rcs "${BUILD}/libopendis6.a" "${BUILD}"/*.o

# ---- Install ---------------------------------------------------------------
echo "installing to ${PREFIX}"
install -d "${PREFIX}/include" "${PREFIX}/lib" "${PREFIX}/share/doc/open-dis-cpp"
cp -R "${DIS6_SRC}/dis6" "${PREFIX}/include/"
find "${PREFIX}/include/dis6" \( -name '*.cpp' -o -name 'CMakeLists.txt' \) -delete
install -m 644 "${GEN}/dis6/opendis6_export.h" "${PREFIX}/include/dis6/opendis6_export.h"
install -m 644 "${BUILD}/libopendis6.a" "${PREFIX}/lib/libopendis6.a"
install -m 644 "${SRC_DIR}/LICENSE" "${PREFIX}/share/doc/open-dis-cpp/LICENSE"
cat > "${PREFIX}/share/doc/open-dis-cpp/PROVENANCE" <<EOF
open-dis-cpp v${VERSION} (https://github.com/open-dis/open-dis-cpp)
License: BSD-2-Clause (LICENSE alongside this file)
Built and installed by scripts/install_open_dis.sh: src/dis6 only, static,
no local modifications. Tarball sha256: ${TARBALL_SHA256}
EOF
echo "done: ${PREFIX}/lib/libopendis6.a, ${PREFIX}/include/dis6/"
