#!/usr/bin/env python3
"""make_example_csv.py — regenerates tools/simulator/data/example_mission.csv.

stdlib-only, deterministic (fixed RNG seed — never system time). Produces 61
one-second frames (t = 0..60 inclusive) of:

  - 1 primary satellite: 550 km altitude, 53 deg inclination circular LEO
    orbit; positions/velocities are sampled per step from the same
    closed-form circular-orbit parametrization used by
    tools/simulator/src/generator.cpp (velocity is the exact analytic derivative
    of position, so the pair is physically consistent at every step).
  - 65 tracked objects with a fixed, exact mix (not randomly proportioned,
    since the count is small): 12 moving debris (circular LEO shells),
    4 other satellites (same orbital family), 2 comets (slow bounded radial
    drift far from Earth), 3 stationary stars (fixed direction, no
    velocity), 4 stationary ground-hot objects (fixed lat/lon, intensities
    500-1500 K, one flagged HIGHLIGHT), and 40 unknown-type objects (30
    orbiting LEO-to-MEO with velocity, 10 stationary position-only
    detections; low confidence). The unknowns cycle through all three CSV
    spellings of the unknown type — "unknown", "0", and an empty cell — so
    the example exercises each one.

  The unknowns are appended after every other object and draw from the RNG
  last, so objects 100-124 are byte-identical to the pre-unknown file.

Run: `python3 scripts/make_example_csv.py` from anywhere; it always writes
to tools/simulator/data/example_mission.csv relative to the repo root (this
script's parent directory's parent).
"""

import math
import os
import random

# ---------------------------------------------------------------------------
# Physical constants — mirror tools/simulator/src/generator.cpp so the example
# scenario is consistent with the C++ generator's orbital model.
# ---------------------------------------------------------------------------
EARTH_RADIUS_M = 6_371_000.0
MU_EARTH = 3.986004418e14  # standard gravitational parameter, m^3/s^2

DURATION_S = 60
STEP_S = 1
SEED = 20260701  # fixed; never time-based, keeps the file byte-reproducible

HIGHLIGHT_FLAG = 2
TYPE_NAMES = {0: "unknown", 1: "debris", 2: "star", 3: "comet", 4: "satellite", 5: "ground_hot"}

NUM_UNKNOWN_MOVING = 30
NUM_UNKNOWN_STATIONARY = 10
# The three equivalent CSV spellings of an unknown type, cycled by object id.
UNKNOWN_TYPE_CELLS = ("unknown", "0", "")

CSV_HEADER = (
    "time_s,kind,id,type,px_m,py_m,pz_m,vx_mps,vy_mps,vz_mps,confidence,intensity,flags"
)

CSV_COMMENT_BLOCK = """\
# example_mission.csv — generated by scripts/make_example_csv.py (do not
# hand-edit; re-run the script instead).
#
# CSV FORMAT (see tools/simulator/src/csv_reader.hpp for the authoritative
# contract):
#   Header: time_s,kind,id,type,px_m,py_m,pz_m,vx_mps,vy_mps,vz_mps,
#           confidence,intensity,flags
#   - kind: "sat" (primary satellite; type ignored) or "obj".
#   - type: unknown|debris|star|comet|satellite|ground_hot, numeric 0-5, or empty (= unknown).
#   - vx/vy/vz: all empty => no velocity; otherwise all three required.
#   - confidence: 0-100 (empty => 100). intensity: float (empty => 0).
#   - flags: empty => 0; only bit1 (2, HIGHLIGHT) may be set here — the
#     has-velocity bit is derived automatically from the velocity cells.
#   - lines starting with '#' and blank lines are skipped.
#
# Scenario: 1 satellite (550 km / 53 deg circular LEO) + 12 moving debris +
# 4 other satellites + 2 comets + 3 stationary stars + 4 stationary
# ground-hot objects (one HIGHLIGHT-flagged) + 40 unknown-type objects (30
# orbiting, 10 stationary; type cell cycles "unknown" / "0" / empty),
# sampled at 1 Hz from t=0..60s.
"""


def rotate_incl_raan(x_orb, y_orb, incl, raan):
  """Rotates an in-plane vector by inclination (about x) then RAAN (about z).

  Applied identically to position and its time-derivative below, since the
  rotation is fixed/time-independent and linear.
  """
  y1 = y_orb * math.cos(incl)
  z1 = y_orb * math.sin(incl)
  x1 = x_orb
  cr, sr = math.cos(raan), math.sin(raan)
  return (x1 * cr - y1 * sr, x1 * sr + y1 * cr, z1)


def circular_orbit_state(r, incl, raan, phase0, omega, t):
  """Standard circular-orbit position + exact-derivative velocity at time t."""
  ang = phase0 + omega * t
  x_orb = r * math.cos(ang)
  y_orb = r * math.sin(ang)
  vx_orb = -r * omega * math.sin(ang)
  vy_orb = r * omega * math.cos(ang)
  px, py, pz = rotate_incl_raan(x_orb, y_orb, incl, raan)
  vx, vy, vz = rotate_incl_raan(vx_orb, vy_orb, incl, raan)
  return px, py, pz, vx, vy, vz


def f3(x):
  return f"{x:.3f}"


def f2(x):
  return f"{x:.2f}"


def build_objects(rng):
  """Returns the fixed list of 65 tracked-object definitions (exact mix)."""
  objects = []
  next_id = 100

  # 12 moving debris: circular LEO shells, 400-2000 km, random incl/RAAN/phase.
  for _ in range(12):
    alt = rng.uniform(400_000.0, 2_000_000.0)
    r = EARTH_RADIUS_M + alt
    objects.append({
        "id": next_id,
        "type": 1,
        "r": r,
        "incl": rng.uniform(0.0, math.pi),
        "raan": rng.uniform(0.0, 2 * math.pi),
        "phase0": rng.uniform(0.0, 2 * math.pi),
        "omega": math.sqrt(MU_EARTH / r ** 3),
        "confidence": rng.randint(50, 100),
    })
    next_id += 1

  # 4 other satellites: same orbital family, tagged type 4.
  for _ in range(4):
    alt = rng.uniform(400_000.0, 2_000_000.0)
    r = EARTH_RADIUS_M + alt
    objects.append({
        "id": next_id,
        "type": 4,
        "r": r,
        "incl": rng.uniform(0.0, math.pi),
        "raan": rng.uniform(0.0, 2 * math.pi),
        "phase0": rng.uniform(0.0, 2 * math.pi),
        "omega": math.sqrt(MU_EARTH / r ** 3),
        "confidence": rng.randint(50, 100),
    })
    next_id += 1

  # 2 comets: far away, slow bounded sinusoidal radial drift (stays finite).
  for _ in range(2):
    theta = rng.uniform(0.0, math.pi)
    phi = rng.uniform(0.0, 2 * math.pi)
    period_s = rng.uniform(5 * 3600.0, 50 * 3600.0)
    objects.append({
        "id": next_id,
        "type": 3,
        "dir": (math.sin(theta) * math.cos(phi), math.sin(theta) * math.sin(phi),
                math.cos(theta)),
        "r0": rng.uniform(5e10, 2e11),
        "amp": rng.uniform(1e8, 1e9),
        "omega": 2 * math.pi / period_s,
        "phase": rng.uniform(0.0, 2 * math.pi),
        "confidence": rng.randint(50, 100),
    })
    next_id += 1

  # 3 stars: fixed direction * 1e12 m, no velocity.
  for _ in range(3):
    theta = rng.uniform(0.0, math.pi)
    phi = rng.uniform(0.0, 2 * math.pi)
    radius = 1e12
    objects.append({
        "id": next_id,
        "type": 2,
        "pos": (radius * math.sin(theta) * math.cos(phi),
                radius * math.sin(theta) * math.sin(phi),
                radius * math.cos(theta)),
        "intensity": rng.uniform(1.0, 6.0),  # apparent magnitude
        "confidence": 100,
    })
    next_id += 1

  # 4 ground-hot: fixed lat/lon, stationary; one HIGHLIGHT-flagged.
  for i in range(4):
    lat = math.radians(rng.uniform(-60.0, 60.0))
    lon = math.radians(rng.uniform(-180.0, 180.0))
    pos = (
        EARTH_RADIUS_M * math.cos(lat) * math.cos(lon),
        EARTH_RADIUS_M * math.cos(lat) * math.sin(lon),
        EARTH_RADIUS_M * math.sin(lat),
    )
    objects.append({
        "id": next_id,
        "type": 5,
        "pos": pos,
        "intensity": rng.uniform(500.0, 1500.0),  # Kelvin
        "confidence": rng.randint(60, 100),
        "flags": HIGHLIGHT_FLAG if i == 0 else 0,
    })
    next_id += 1

  # 30 moving unknowns: circular orbits from LEO out to MEO, low confidence.
  for _ in range(NUM_UNKNOWN_MOVING):
    alt = rng.uniform(400_000.0, 20_000_000.0)
    r = EARTH_RADIUS_M + alt
    objects.append({
        "id": next_id,
        "type": 0,
        "r": r,
        "incl": rng.uniform(0.0, math.pi),
        "raan": rng.uniform(0.0, 2 * math.pi),
        "phase0": rng.uniform(0.0, 2 * math.pi),
        "omega": math.sqrt(MU_EARTH / r ** 3),
        "confidence": rng.randint(10, 70),
    })
    next_id += 1

  # 10 stationary unknowns: position-only detections (no velocity) at a
  # random direction and LEO-to-GEO range.
  for _ in range(NUM_UNKNOWN_STATIONARY):
    theta = rng.uniform(0.0, math.pi)
    phi = rng.uniform(0.0, 2 * math.pi)
    radius = EARTH_RADIUS_M + rng.uniform(400_000.0, 36_000_000.0)
    objects.append({
        "id": next_id,
        "type": 0,
        "stationary": True,
        "pos": (radius * math.sin(theta) * math.cos(phi),
                radius * math.sin(theta) * math.sin(phi),
                radius * math.cos(theta)),
        "confidence": rng.randint(10, 50),
    })
    next_id += 1

  return objects


def object_row(t, obj):
  type_name = TYPE_NAMES[obj["type"]]
  if obj["type"] == 0:
    type_name = UNKNOWN_TYPE_CELLS[obj["id"] % len(UNKNOWN_TYPE_CELLS)]
    if obj.get("stationary"):
      px, py, pz = obj["pos"]
      return (str(t), "obj", str(obj["id"]), type_name, f3(px), f3(py), f3(pz), "", "", "",
              str(obj["confidence"]), "", "")
  if obj["type"] in (0, 1, 4):
    px, py, pz, vx, vy, vz = circular_orbit_state(
        obj["r"], obj["incl"], obj["raan"], obj["phase0"], obj["omega"], t)
    return (str(t), "obj", str(obj["id"]), type_name, f3(px), f3(py), f3(pz), f3(vx), f3(vy),
            f3(vz), str(obj["confidence"]), "", "")
  if obj["type"] == 3:
    phase = obj["omega"] * t + obj["phase"]
    radius = obj["r0"] + obj["amp"] * math.sin(phase)
    rate = obj["amp"] * obj["omega"] * math.cos(phase)
    dx, dy, dz = obj["dir"]
    px, py, pz = dx * radius, dy * radius, dz * radius
    vx, vy, vz = dx * rate, dy * rate, dz * rate
    return (str(t), "obj", str(obj["id"]), type_name, f3(px), f3(py), f3(pz), f3(vx), f3(vy),
            f3(vz), str(obj["confidence"]), "", "")
  if obj["type"] == 2:
    px, py, pz = obj["pos"]
    return (str(t), "obj", str(obj["id"]), type_name, f3(px), f3(py), f3(pz), "", "", "",
            str(obj["confidence"]), f2(obj["intensity"]), "")
  # ground_hot
  px, py, pz = obj["pos"]
  return (str(t), "obj", str(obj["id"]), type_name, f3(px), f3(py), f3(pz), "", "", "",
          str(obj["confidence"]), f2(obj["intensity"]), str(obj["flags"]))


def main():
  script_dir = os.path.dirname(os.path.abspath(__file__))
  repo_root = os.path.dirname(script_dir)
  out_path = os.path.join(repo_root, "tools", "simulator", "data", "example_mission.csv")

  rng = random.Random(SEED)

  sat_r = EARTH_RADIUS_M + 550_000.0  # 550 km altitude
  sat_incl = math.radians(53.0)
  sat_omega = math.sqrt(MU_EARTH / sat_r ** 3)

  objects = build_objects(rng)

  lines = [CSV_COMMENT_BLOCK.rstrip("\n"), CSV_HEADER]
  steps = DURATION_S // STEP_S + 1
  for step in range(steps):
    t = step * STEP_S
    spx, spy, spz, svx, svy, svz = circular_orbit_state(sat_r, sat_incl, 0.0, 0.0, sat_omega, t)
    sat_row = (str(t), "sat", "1", "", f3(spx), f3(spy), f3(spz), f3(svx), f3(svy), f3(svz), "",
               "", "")
    lines.append(",".join(sat_row))
    for obj in objects:
      lines.append(",".join(object_row(t, obj)))

  content = "\n".join(lines) + "\n"

  os.makedirs(os.path.dirname(out_path), exist_ok=True)
  with open(out_path, "w", encoding="utf-8") as f:
    f.write(content)

  num_data_rows = steps * (1 + len(objects))
  print(f"wrote {out_path}")
  print(f"  frames (timesteps): {steps}")
  print(f"  objects per frame: {len(objects)}")
  print(f"  data rows: {num_data_rows}")
  print(f"  file size: {os.path.getsize(out_path)} bytes")


if __name__ == "__main__":
  main()
